### ISSUE TITLE
can't add more than one author

### ISSUE THREAD

**Issue by danbjoseph** [samesies/barber-jekyll#19]
adjusting the `_config.yml` file as follows
```yaml
# Author settings
author:
  - name: Thomas Vaeth
    bio: Thomas Vaeth was born in New York, raised in Pennsylvania, and transplanted in Washington. He was a Web Developer at Urban Influence, but now he's a Software Engineer at Getty Images.
    url: http://thomasvaeth.com
  - name: me
    bio: a real person
    url: https://me.github.io
```
results in a repeat at the bottom of posts?
![Screen Shot 2019-08-07 at 1 53 12 PM](https://user-images.githubusercontent.com/4806884/62645769-e5f77980-b91a-11e9-89e1-f0cd1ac089ea.png)
